version: '2'

services:
  db:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senharoot
      MYSQL_DATABASE: data-base-name
      MYSQL_USER: data-base-user
      MYSQL_PASSWORD: senha-data-base-user

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./www:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: data-base-name
      WORDPRESS_DB_USER: ata-base-user
      WORDPRESS_DB_PASSWORD: senha-data-base-user
volumes:
    db_data:
