version: '2'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    volumes:
      - ./www:/var/www/html
    environment:
      WORDPRESS_DB_PASSWORD: root

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root